### ISSUE TITLE
Download link for WRS shapefiles is outdated

### ISSUE THREAD

**Issue by WortalMombat** [yannforget/pylandsat#5]
When syncing the database the following error appeared:
`requests.exceptions.HTTPError: 404`

USGS has moved the WRS shapefile to https://prd-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/atoms/files/WRS2_descending_0.zip.

I changed the link in the `sync_wrs()` function of the `database.py` module which solved the problem for me.

**Comment by konstantinos2018** [comment]
@WortalMombat Hi Wortal, you're right! The hyperlinks, also, are different for Landsat 1-3 and Landsat 4-8, which can be found here: https://www.usgs.gov/core-science-systems/nli/landsat/landsat-shapefiles-and-kml-files

**Comment by yannforget** [comment]
Thanks, this should be fixed in v0.5

**Comment by IlliaOvcharenko** [comment]
I had a similar issue, got an `HTTP Error 403` during WRS downloading. I changed a downloading link, it seems to work okay 
```WRS_URL = "https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/atoms/files/WRS2_descending_0.zip"```
